environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

install:
  - ps: if (-not(Test-Path($env:PYTHON))) { & _appveyor\install-python.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\Program Files (x86)\\NSIS\\Bin;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - "python -m pip install --disable-pip-version-check --upgrade pip"
  - "pip install --upgrade pipenv"
  - "pipenv install --system --dev --skip-lock"

build: off

test_script:
  - "flake8 ."
  - "pytest tests"

after_test:
  - "for /f %%i in ('git describe') do @set SNAFU_GIT_VERSION=%%i"
  - "python .\\installers\\build.py win32 %SNAFU_GIT_VERSION%"
  - "python .\\installers\\build.py amd64 %SNAFU_GIT_VERSION%"
  - ps: "ls .\\installers\\*.exe"

artifacts:
  - path: ".\\installers\\*.exe"
