image: Visual Studio 2015

max_jobs: 2

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      INSTALLER_ARCH: "amd64"
    - PYTHON: "C:\\Python36"
      INSTALLER_ARCH: "win32"

platform:
  - x86
  - x64

matrix:
  exclude:
    - platform: x86
      PYTHON: "C:\\Python36-x64"
    - platform: x64
      PYTHON: "C:\\Python36"

install:
  - "SET PATH=%PATH%;C:\\Program Files (x86)\\NSIS\\Bin"

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --disable-pip-version-check --upgrade pip"
  - "pip install --upgrade pipenv"
  - "pipenv install --system --dev --skip-lock"

  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain 1.9.0
  - "SET PATH=%USERPROFILE%\.cargo\bin;%PATH%"

build: off

test_script:
  - "flake8 ."
  - "pytest tests"

after_test:
  - "for /f %%i in ('git describe') do @set SNAFU_GIT_VERSION=%%i"
  - "python .\\installers\\build.py %SNAFU_GIT_VERSION%"
  - ps: "ls .\\installers\\*.exe"

artifacts:
  - path: ".\\installers\\*.exe"
