[package]
name = "pythonup"
version = "0.1.0"
authors = ["Tzu-ping Chung <uranusjr@gmail.com>"]

[dependencies]
winapi = { version = "0.3.2", features = ["consoleapi", "jobapi2", "wincon"] }
winreg = "0.5.0"

[lib]
name = "pythonup"
path = "src/lib.rs"
