[package]
name = "snafu"
version = "0.1.0"
authors = ["Tzu-ping Chung <uranusjr@gmail.com>"]

[dependencies]
kernel32-sys = "0.2.2"
winapi = "0.2.8"
winreg = "0.4"

[[bin]]
name = "snafu"
path = "src/main.rs"

[lib]
name = "snafu"
path = "src/lib.rs"
